@set adsk_3dsmax_x64_2017=c:\program files\autodesk\3ds max 2017\
@set adsk_3dsmax_x64_2018=c:\program files\autodesk\3ds max 2018\
@set allusersprofile=c:\programdata
@set appdata=c:\users\ewout\appdata\roaming
@set commandprompttype=native
@set commonprogramfiles=c:\program files\common files
@set commonprogramfiles(x86)=c:\program files (x86)\common files
@set commonprogramw6432=c:\program files\common files
@set complus_installroot=
@set complus_version=
@set computername=desktop-i2n37bu
@set comspec=c:\windows\system32\cmd.exe
@set devenvdir=c:\program files (x86)\microsoft visual studio\2017\enterprise\common7\ide\
@set extensionsdkdir=c:\program files (x86)\microsoft sdks\windows kits\10\extensionsdks
@set fps_browser_app_profile_string=internet explorer
@set fps_browser_user_profile_string=default
@set framework40version=v4.0
@set frameworkdir=c:\windows\microsoft.net\framework64\
@set frameworkdir64=c:\windows\microsoft.net\framework64
@set frameworkversion=v4.0.30319
@set frameworkversion64=v4.0.30319
@set fsharpinstalldir=c:\program files (x86)\microsoft sdks\f#\4.1\framework\v4.0\
@set fxc2_dir=f:\school\graphics programming 2\tools\fx composer
@set gtk_basepath=c:\program files (x86)\gtksharp\2.12\
@set homedrive=c:
@set homepath=\users\ewout
@set include=c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.11.25503\atlmfc\include;c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.11.25503\include;c:\program files (x86)\windows kits\netfxsdk\4.6.1\include\um;c:\program files (x86)\windows kits\10\include\10.0.15063.0\ucrt;c:\program files (x86)\windows kits\10\include\10.0.15063.0\shared;c:\program files (x86)\windows kits\10\include\10.0.15063.0\um;c:\program files (x86)\windows kits\10\include\10.0.15063.0\winrt
@set lib=c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.11.25503\atlmfc\lib\x64;c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.11.25503\lib\x64;c:\program files (x86)\windows kits\netfxsdk\4.6.1\lib\um\x64;c:\program files (x86)\windows kits\10\lib\10.0.15063.0\ucrt\x64;c:\program files (x86)\windows kits\10\lib\10.0.15063.0\um\x64
@set libpath=c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.11.25503\atlmfc\lib\x64;c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.11.25503\lib\x64;c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.11.25503\lib\x86\store\references;c:\program files (x86)\windows kits\10\unionmetadata\10.0.15063.0\;c:\program files (x86)\windows kits\10\references\10.0.15063.0\;c:\windows\microsoft.net\framework64\v4.0.30319
@set localappdata=c:\users\ewout\appdata\local
@set logonserver=\\desktop-i2n37bu
@set msbuildloadmicrosofttargetsreadonly=true
@set msbuildsdkspath=c:\program files (x86)\microsoft visual studio\2017\enterprise\msbuild\sdks
@set msbuild_exe_path=c:\program files (x86)\pvs-studio\buildtools15\msbuild.exe
@set netfxsdkdir=c:\program files (x86)\windows kits\netfxsdk\4.6.1\
@set number_of_processors=8
@set nvidiawhitelisted=0x01
@set onedrive=c:\users\ewout\onedrive
@set onlineservices=online services
@set os=windows_nt
@set path=c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.11.25503\bin\hostx64\x64;c:\program files (x86)\microsoft visual studio\2017\enterprise\common7\ide\vc\vcpackages;c:\program files (x86)\microsoft sdks\typescript\2.3;c:\program files (x86)\microsoft visual studio\2017\enterprise\common7\ide\commonextensions\microsoft\testwindow;c:\program files (x86)\microsoft visual studio\2017\enterprise\common7\ide\commonextensions\microsoft\teamfoundation\team explorer;c:\program files (x86)\microsoft visual studio\2017\enterprise\msbuild\15.0\bin\roslyn;c:\program files (x86)\microsoft visual studio\2017\enterprise\team tools\performance tools;c:\program files (x86)\microsoft visual studio\shared\common\vsperfcollectiontools\;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools\x64\;c:\program files (x86)\microsoft sdks\f#\4.1\framework\v4.0\;c:\program files (x86)\windows kits\10\bin\x64;c:\program files (x86)\windows kits\10\bin\10.0.15063.0\x64;c:\program files (x86)\microsoft visual studio\2017\enterprise\\msbuild\15.0\bin;c:\windows\microsoft.net\framework64\v4.0.30319;c:\program files (x86)\microsoft visual studio\2017\enterprise\common7\ide\;c:\program files (x86)\microsoft visual studio\2017\enterprise\common7\tools\;c:\program files (x86)\nvidia corporation\physx\common;c:\programdata\oracle\java\javapath;c:\program files (x86)\intel\icls client\;c:\program files\intel\icls client\;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\program files (x86)\hp\hp performance advisor;c:\program files (x86)\intel\intel(r) management engine components\dal;c:\program files\intel\intel(r) management engine components\dal;c:\program files (x86)\intel\intel(r) management engine components\ipt;c:\program files\intel\intel(r) management engine components\ipt;c:\windows\system32\config\systemprofile\.dnx\bin;c:\program files\microsoft dnx\dnvm\;c:\program files\microsoft sql server\120\tools\binn\;c:\program files\microsoft sql server\130\tools\binn\;c:\program files\git\cmd;c:\program files\common files\autodesk shared\;c:\program files (x86)\nodejs\;c:\program files (x86)\skype\phone\;c:\program files (x86)\windows live\shared;c:\program files (x86)\autodesk\backburner\;c:\program files\dotnet\;c:\program files (x86)\gtksharp\2.12\bin;c:\program files\mysql\mysql utilities 1.6\;c:\program files\intel\wifi\bin\;c:\program files\common files\intel\wirelesscommon\;c:\program files (x86)\visual leak detector\bin\win32;c:\program files (x86)\visual leak detector\bin\win64;c:\program files\perforce\;c:\users\ewout\appdata\local\microsoft\windowsapps;c:\users\ewout\appdata\roaming\npm
@set pathext=.com;.exe;.bat;.cmd;.vbs;.vbe;.js;.jse;.wsf;.wsh;.msc
@set pkgdefapplicationconfigfile=c:\users\ewout\appdata\local\microsoft\visualstudio\15.0_1c8cbf76\devenv.exe.config
@set platform=x64
@set platformcode=ta
@set processor_architecture=amd64
@set processor_identifier=intel64 family 6 model 94 stepping 3, genuineintel
@set processor_level=6
@set processor_revision=5e03
@set programdata=c:\programdata
@set programfiles=c:\program files
@set programfiles(x86)=c:\program files (x86)
@set programw6432=c:\program files
@set prompt=$p$g
@set psmodulepath=c:\program files\windowspowershell\modules;c:\windows\system32\windowspowershell\v1.0\modules
@set ptsminstallpath_x86=c:\program files (x86)\hewlett-packard\hp protecttools security manager\
@set public=c:\users\public
@set pvsbuildtoolsextensionspath=c:\program files (x86)\microsoft visual studio\2017\enterprise\msbuild
@set pvs_vsinstalldir=c:\program files (x86)\microsoft visual studio\2017\enterprise
@set python_root=f:\school\graphics programming 2\tools\fx composer\python\
@set regioncode=emea
@set sessionname=console
@set shim_mccompat=0x810000001
@set systemdrive=c:
@set systemroot=c:\windows
@set temp=c:\users\ewout\appdata\local\temp
@set tmp=c:\users\ewout\appdata\local\temp
@set ucrtversion=10.0.15063.0
@set universalcrtsdkdir=c:\program files (x86)\windows kits\10\
@set userdomain=desktop-i2n37bu
@set userdomain_roamingprofile=desktop-i2n37bu
@set username=ewout
@set userprofile=c:\users\ewout
@set vcideinstalldir=c:\program files (x86)\microsoft visual studio\2017\enterprise\common7\ide\vc\
@set vcinstalldir=c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\
@set vctoolsinstalldir=c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.11.25503\
@set visualstudiodir=c:\users\ewout\documents\visual studio 2017
@set visualstudioedition=microsoft visual studio enterprise 2017
@set visualstudioversion=15.0
@set vs110comntools=c:\program files (x86)\microsoft visual studio 11.0\common7\tools\
@set vs120comntools=c:\program files (x86)\microsoft visual studio 12.0\common7\tools\
@set vs140comntools=c:\program files (x86)\microsoft visual studio 14.0\common7\tools\
@set vs150comntools=c:\program files (x86)\microsoft visual studio\2017\enterprise\common7\tools\
@set vsappiddir=c:\program files (x86)\microsoft visual studio\2017\enterprise\common7\ide\
@set vsappidname=devenv.exe
@set vscmd_arg_app_plat=desktop
@set vscmd_arg_host_arch=x64
@set vscmd_arg_tgt_arch=x64
@set vscmd_ver=15.0.26730.16
@set vsinstalldir=c:\program files (x86)\microsoft visual studio\2017\enterprise\
@set vslang=1033
@set vssdk140install=c:\program files (x86)\microsoft visual studio 14.0\vssdk\
@set vssdk150install=c:\program files (x86)\microsoft visual studio\2017\enterprise\vssdk
@set vsskuedition=enterprise
@set windir=c:\windows
@set windowslibpath=c:\program files (x86)\windows kits\10\unionmetadata\10.0.15063.0\;c:\program files (x86)\windows kits\10\references\10.0.15063.0\
@set windowssdkbinpath=c:\program files (x86)\windows kits\10\bin\
@set windowssdkdir=c:\program files (x86)\windows kits\10\
@set windowssdklibversion=10.0.15063.0\
@set windowssdkverbinpath=c:\program files (x86)\windows kits\10\bin\10.0.15063.0\
@set windowssdkversion=10.0.15063.0\
@set windowssdk_executablepath_x64=c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools\x64\
@set windowssdk_executablepath_x86=c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools\
@set __dotnet_add_64bit=1
@set __dotnet_preferred_bitness=64
@set __vscmd_preinit_path=c:\program files (x86)\nvidia corporation\physx\common;c:\programdata\oracle\java\javapath;c:\program files (x86)\intel\icls client\;c:\program files\intel\icls client\;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\program files (x86)\hp\hp performance advisor;c:\program files (x86)\intel\intel(r) management engine components\dal;c:\program files\intel\intel(r) management engine components\dal;c:\program files (x86)\intel\intel(r) management engine components\ipt;c:\program files\intel\intel(r) management engine components\ipt;c:\windows\system32\config\systemprofile\.dnx\bin;c:\program files\microsoft dnx\dnvm\;c:\program files\microsoft sql server\120\tools\binn\;c:\program files\microsoft sql server\130\tools\binn\;c:\program files\git\cmd;c:\program files\common files\autodesk shared\;c:\program files (x86)\nodejs\;c:\program files (x86)\skype\phone\;c:\program files (x86)\windows live\shared;c:\program files (x86)\autodesk\backburner\;c:\program files\dotnet\;c:\program files (x86)\gtksharp\2.12\bin;c:\program files\mysql\mysql utilities 1.6\;c:\program files\intel\wifi\bin\;c:\program files\common files\intel\wirelesscommon\;c:\program files (x86)\visual leak detector\bin\win32;c:\program files (x86)\visual leak detector\bin\win64;c:\program files\perforce\;c:\users\ewout\appdata\local\microsoft\windowsapps;c:\users\ewout\appdata\roaming\npm

@call cl.exe